name: Build

on:
  - push
  - pull_request

env:
  'default-python-version': '3.10'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.default-python-version }}
    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch hatch-vcs
    - run: hatch run tests

    
  build:
    name: Build zip dist and possibly make release
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # lfs: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.default-python-version }}

    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch hatch-vcs

    - run: hatch build --clean --target zipped-directory

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.zip

    - name: classify tag
      id: classify-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[[:digit:]]+(\.[[:digit:]]+){2}$ ]]; then
          echo "is_release=true" >> $GITHUB_ENV
        fi

    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.zip
        fail_on_unmatched_files: true
        generate_release_notes: true
        draft: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        prerelease: ${{ env.is_release != 'true' }}
